lifeline-backend-master/apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetConfirmView
from rest_auth import views as rest_views

from apps.accounts.views import UsersViewSet, UserLanguageView, UserActivityView, UserCommonActivityView

urlpatterns = [
    url('update-profile', UserLanguageView.as_view({'post': 'create'}), name='update_profile'),
    url('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url('^password/reset/$', rest_views.PasswordResetView.as_view(), name='rest_password_reset'),
    url('^password/reset/confirm/$', rest_views.PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url('^activity/$', UserActivityView.as_view(), name='user_activity'),
    url('^common/activity/$', UserCommonActivityView.as_view(), name='common_user_activity'),
    url('^$', UsersViewSet.as_view({'get': 'list'}), name='users')

]

lifeline-backend-master/lifeline/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import RedirectView

from lifeline.swagger import get_swagger_view


def handler404(request):
    return render(request, '404.html')


urlpatterns = [
    url('api/v1/', include('lifeline.api_v1_urls')),
    url('docs/', get_swagger_view(title='Lifeline API'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    url('admin/', include(admin.site.urls)),
    url('^$', RedirectView.as_view(url='admin/', permanent=False), name='index'),
    prefix_default_language=False
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lifeline-backend-master/apps/accounts/models.py
import uuid

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel

from apps.accounts import choices
from apps.accounts.managers import AccountManager


class User(AbstractUser):
    username = models.CharField(_('Username'), blank=True, null=True, max_length=255)
    phone = models.CharField(_('Mobile'), max_length=255, blank=True, null=True)
    line = models.CharField(_('Direct line'), max_length=255, blank=True, null=True)
    inami = models.CharField(
        _('INAMI number (accredited number for healthcare professional) '), max_length=255, blank=True, null=True
    )
    language = models.CharField(_('User language'), max_length=16, choices=settings.LANGUAGES, default='en')
    email = models.EmailField(_('Email address'), unique=True)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    gender = models.CharField(_('Gender'), max_length=1, choices=choices.SEX, null=True)
    units = models.ManyToManyField('units.Unit')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = AccountManager()

    def __str__(self):
        return self.username or self.email

    def save(self, *args, **kwargs):
        self.username = f'{self.first_name} {self.last_name}'.strip() \
            if self.first_name or self.last_name else self.email
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        ordering = ('date_joined',)


class Activity(TimeStampedModel):
    user = models.CharField(_('Username'), max_length=255)
    email = models.CharField(_('User email'), max_length=255)
    file_id = models.CharField(_('Patient file id'), max_length=255, null=True, blank=True)
    patient = models.CharField(_('Patient name'), max_length=255, null=True, blank=True)
    patient_id = models.CharField(_('Patient id'), max_length=255, null=True, blank=True)
    activity = models.TextField(blank=True, null=True)
    data = models.TextField(_('Data'), null=True)

    class Meta:
        verbose_name = _('User activity')
        verbose_name_plural = _('Users activities')
        db_table = 'user_activities'
        ordering = ('-created',)


class AdminActivity(models.Model):
    log_entry = models.ForeignKey(
        'admin.LogEntry', verbose_name=_('LogEntry'), on_delete=models.CASCADE, null=True
    )
    patient_id = models.CharField(_('Patient id'), max_length=16)

    class Meta:
        verbose_name = _('Admin User activity')
        verbose_name_plural = _('Admin Users activities')
        db_table = 'admin_activities'

lifeline-backend-master/apps/accounts/forms.py
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.forms import CharField, ModelMultipleChoiceField, ModelForm
from django.utils.translation import ugettext_lazy as _

from apps.accounts.models import User
from apps.units.services import get_all_units


class UserAddForm(UserCreationForm):
    groups = ModelMultipleChoiceField(label=_('Role'), queryset=Group.objects.all())
    units = ModelMultipleChoiceField(label=_('Unit'), queryset=get_all_units())
    last_name = CharField(required=True)


class UserUpdateForm(UserChangeForm):
    groups = ModelMultipleChoiceField(label=_('Role'), queryset=Group.objects.all())


class UserAddPermissionForm(ModelForm):
    users = ModelMultipleChoiceField(
        label=_('User'), queryset=User.objects.all(), widget=FilteredSelectMultiple('Users', is_stacked=True),
        required=False
    )

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        if instance:
            initial = kwargs.setdefault('initial', {})
            initial['users'] = [user.pk for user in instance.user_set.all()]
        super().__init__(*args, **kwargs)

    class Meta:
        model = Group
        fields = ('name', 'permissions',)

    def clean_users(self):
        selected_users = self.cleaned_data['users']
        if self.instance.id:
            for user in self.instance.user_set.all():
                if user not in selected_users and user.groups.count() == 1:
                    raise ValidationError(f'{user}: should have at least 1 role', code='invalid')
        return selected_users

    def save(self, commit=True):
        instance = super().save(False)
        _save_m2m = self.save_m2m

        def save_m2m():
            _save_m2m()
            instance.user_set.clear()
            instance.user_set.add(*self.cleaned_data['users'])
        self.save_m2m = save_m2m
        if commit:
            instance.save()
            self.save_m2m()
        return instance

lifeline-backend-master/apps/accounts/views.py
from datetime import date
from dateutil.relativedelta import relativedelta

from django.http import Http404
from rest_framework import mixins, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ReadOnlyModelViewSet, GenericViewSet
from rest_framework_jwt.views import ObtainJSONWebToken

from apps.accounts.serializers import UserSerializer, UserDetailsSerializer
from apps.accounts.services import get_all_users, get_user_by_uuid, get_log_entry_actions, get_user_activity, \
    get_active_users, clear_brusafe_token
from apps.patients.services import get_archived_files, get_admission_files
from apps.utils.views import BaseExportView
from apps.wish.permissions import WishPermission
from apps.wish.services import create_wish_connection


class UsersViewSet(ReadOnlyModelViewSet):
    """
    get:
    Return a list of all the existing users.
    """
    queryset = get_all_users()
    serializer_class = UserSerializer
    pagination_class = None
    permission_classes = (IsAuthenticated,)


class UserLanguageView(mixins.CreateModelMixin, GenericViewSet):
    """
    create:
    Updates user-senders first name, last name and language
    """
    http_method_names = ['head', 'options', 'post', 'get']
    queryset = get_all_users()
    serializer_class = UserDetailsSerializer
    pagination_class = None
    permission_classes = (IsAuthenticated,)

    def create(self, request, *args, **kwargs):
        serializer = UserDetailsSerializer(request.user, data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data)


class UserActivityView(BaseExportView):
    """
    get:
    Returns a pdf file, containing information about user activities, depending on the query_params in request
    """
    template_path = 'accounts/activity_report.html'

    @classmethod
    def _get_context(cls, request):
        """
        Prepares context for pdf doc, containing info about user.
        gets from query_params, if present:
        user uuid,
        patient (for user activities about this patient)
        start, end (time period of activities)
        :param request: GET request to view
        :return dict:
        {
            'activities': activities query set for Activity model,
            'user': user to be exported,
            'admin': prepare_admin_logs classmethod
        }
        """
        uuid = request.query_params.get('user')
        patient = request.query_params.get('patient')
        start = request.query_params.get('start')
        end = request.query_params.get('end')
        user = get_user_by_uuid(uuid)
        activities = get_user_activity(user.email, patient, start, end)
        return {'activities': activities, 'user': user, 'admin': cls.prepare_admin_logs(uuid, patient, start, end)}

    @classmethod
    def get_export_name(cls, request):
        return get_user_by_uuid(request.query_params.get('user')) or 'user'

    @classmethod
    def prepare_admin_logs(cls, uuid, patient, start, end):
        """
        Prepares logs for admin actions.
        :param uuid: user to be exported,
        :param patient: for user activities about this patient
        :param start: time period of activities
        :param end: time period of activities
        :return list of tuples:
        For each log in queryset to LogEntry list element:
        (action time, content type, object representation, action_mapping staticmethod, change message)
        """
        qs = get_log_entry_actions(uuid, patient, start, end)
        return [(
            f'{log.action_time.strftime("%B %d, %Y, %I:%M %P")}',
            log.content_type,
            log.object_repr,
            cls.action_mapping(log.action_flag),
            log.change_message.replace('[', '').replace(']', '')
        ) for log in qs]

    @staticmethod
    def action_mapping(action_flag):
        """
        Map of actions
        :param action_flag: action flag
        :return str: action text
        """
        actions = {
            1: 'Created',
            2: 'Changed',
            3: 'Deleted',
        }
        return actions[action_flag]


class UserCommonActivityView(BaseExportView):
    """
    get:
    Returns a pdf file, containing information about common user activities, depending on the query_params in request
    """
    template_path = 'accounts/common_activity_report.html'

    period_map = {
        'month': 1,
        'quarter': 3,
        'year': 12,
        'all': 0
    }

    period_name_display = {
        'month': 'current month',
        'quarter': 'current quarter',
        'year': 'current year',
        'all': 'all the time'
    }

    @classmethod
    def _get_context(cls, request):
        """
        Prepares context for pdf doc, containing info about user.
        gets from query_params, if present:
        user uuid,
        patient (for user activities about this patient)
        start, end (time period of activities)
        :param request: GET request to view
        :return dict:
        {
            'active_files': active patient files,
            'archived_files': archived patient files,
            'user': exporting user,
            'users': active users
        }
        OR
        {
            'active_files': active patient files during time period,
            'archived_files': archived patient files during time period,
            'user': exporting user,
            'users': active users,
            'prev': from timestamp,
            'today': to timestamp
        }
        """
        period = request.query_params.get('period')
        block = request.query_params.get('block')
        if not period or period not in cls.period_map:
            raise Http404
        prev = today = date.today()
        if period == 'month':
            prev = today + relativedelta(day=1)
        elif period == 'quarter':
            prev = date(today.year, (today.month - 1) // 3 * 3 + 1, 1)
        elif period == 'year':
            prev = today + relativedelta(day=1, month=1)
        ctx = {
            'active_files': get_admission_files(),
            'archived_files': get_archived_files(),
            'user': request.user,
            'users': get_active_users(),
            'block': block
        }
        if period == 'all':
            ctx.update({'all': True})
            return ctx
        ctx.update({
            'active_files': get_admission_files().filter(created__date__gte=prev),
            'archived_files': get_archived_files().filter(closed_since__gte=prev),
            'prev': prev,
            'next': today,
        })
        return ctx

    @classmethod
    def get_export_name(cls, request):
        return f"activities {cls.period_name_display.get(request.query_params.get('period'))}"


class ObtainJSONWebTokenClearBrusafeToken(ObtainJSONWebToken):
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            user = serializer.object.get('user') or request.user
            os_uuid = request.data.get('os_uuid')
            if os_uuid:
                if not WishPermission().has_permission(user):
                    return Response(status=status.HTTP_403_FORBIDDEN)
                create_wish_connection(user, os_uuid)
            else:
                clear_brusafe_token(user)
        return super().post(request, *args, **kwargs)

lifeline-backend-master/apps/accounts/templates/accounts/activity_report.html
{% load i18n %}
<html lang="en">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<head>
  <style>
    @font-face { font-family: Arial; src: url(fonts/Roboto-Regular.ttf);}
    @page {
        margin: 2cm;
        @frame footer_frame {
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 30pt;
        }
    }
    .underline {
        text-decoration: underline;
    }
    .content-header {
        margin-top: 40px;
        margin-bottom: 10px;
        font-weight: bold;
        font-size: 20px;
    }
    .concerns {
        margin-top: 30px;
    }
    .concerns-item {
        margin: 0;
    }
    .bold {
        font-weight:bold;
    }
    .footer {
       text-align: right;
       font-size: 12px;
       color: gray;
    }
    .type-title {
        font-size: 24px;
        color: blue;
    }
    body {
        font-size: 16px;
    }
  </style>
</head>
<body>
  <table>
     <tr>
        <th style="text-align:left"><img width="400" src="{{ logo }}" alt="logo"></th>
        <th style="text-align:right">
            <div  class="underline type-title">{{ type|upper }}</div>
            <span>{{ created }}</span>
        </th>
     </tr>
  </table>

  {% if user.username != user.email %}
      <div><span class="bold">{% trans 'User Name' %}:</span> {{ user.username }}</div>
  {% endif %}
  <div><span class="bold">{% trans 'User Email' %}:</span> {{ user.email }}</div>
  {% if user.phone %}
      <div><span class="bold">{% trans 'User Mobile' %}:</span> {{ user.phone }}</div>
  {% endif %}
  {% if user.line %}
      <div><span class="bold">{% trans 'User Direct line' %}:</span> {{ user.line }}</div>
  {% endif %}
  {% if user.inami %}
      <div><span class="bold">{% trans 'INAMI number (accredited number for healthcare professional)' %}:</span> {{ user.inami }}</div>
  {% endif %}
  {% if user.gender %}
      <div><span class="bold">{% trans 'Gender' %}:</span> {{ user.get_gender_display }}</div>
  {% endif %}
  {% if user.language %}
      <div><span class="bold">{% trans 'Language' %}:</span> {{ user.get_language_display }}</div>
  {% endif %}
  <br>

  <p class="underline concerns bold">{% trans 'User Application activity' %}:</p>

  {% if not activities %}
    <p>{% trans 'No activity was found for this user.' %}</p>
  {% endif %}

  {% for activity in activities %}
    <div style="margin-top:12px;"><strong>{{ activity.created }}</strong> -
        {% if activity.patient %}{% trans 'Patient' %}: <i>{{ activity.patient }}</i> - {% endif %}
        {% if activity.file_id %}{% trans 'File' %}: <i>{{ activity.file_id }}</i> - {% endif %}
        {% trans 'Action' %}: <i>{{ activity.activity }}</i>
        <div style="margin-top:0px;">{% if activity.data %}{% trans 'Sent data' %}: <i style="font-family: Arial;">{{ activity.data }}</i>{% endif %}</div>
    </div>
  {% endfor %}
  <br>
  <p class="underline concerns bold">{% trans 'Admin Interface Actions' %}:<p>

  {% if not admin %}
    <p>{% trans 'No activity in admin interface was found for this user.' %}</p>
  {% endif %}

  {% for action in admin %}
    <div style="margin-top:10px;"><strong>{{ action.0 }}</strong> -
        {% trans 'Application' %}: <i>{{ action.1 }}</i> -
        {% if action.2 %}{% trans 'Object' %}: <i>{{ action.2 }}</i>{% endif %}
        {% trans 'Action' %}: <i>{{ action.3 }}</i>
    </div>
  {% if action.4 %}<div>Sent data: <i>{{ action.4 }}</i></div>{% endif %}
  {% endfor %}

  <div id="footer_content" class="footer">
    <br>
    {% trans 'Activity report' %}: {{ user.username }} <pdf:pagenumber>/<pdf:pagecount>
  </div>
</body>
</html>

lifeline-backend-master/apps/accounts/templates/accounts/change_list_template.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls admin_static admin_list material_admin %}

{% block extrahead %}
  {{ block.super }}
  <script src="{% static 'accounts/js/common_activities.js' %}"></script>
{% endblock %}

{% block main_content %}
<form method="POST" class="content">
    {% csrf_token %}
    <div class="left-panel{% if action_form or cl.date_hierarchy or cl.list_filter or cl.search_fields %}{% else %} wide{% endif %}">
        <div class="card">
            <div class="card-content">
                {% block result_list %}
                  {{ block.super }}
                {% endblock %}

                {% block pagination %}{{ block.super }}{% endblock %}
            </div>
        </div>
    </div>

    {% if action_form or cl.date_hierarchy or cl.list_filter or cl.search_fields %}
    <div class="right-panel">

        <div class="card filters-card">
          <div class="card-content">
            <span class="card-title">{% trans 'Common user activities' %}</span>
            <div style="text-align: center">
              <select class="select-patient" onchange="setActivityExportParams(event, 'period')">
                <option class="user-item" value="month">{% trans 'Month' %}</option>
                <option class="user-item" value="quarter">{% trans 'Quarter' %}</option>
                <option class="user-item" value="year">{% trans 'Year' %}</option>
                <option class="user-item" value="all">{% trans 'All the time' %}</option>
              </select>
              <select class="select-patient" onchange="setActivityExportParams(event, 'block')">
                <option class="user-item" value="all-info">{% trans 'All info' %}</option>
                <option class="user-item" value="created">{% trans 'Created Files' %}</option>
                <option class="user-item" value="archived">{% trans 'Archived Files' %}</option>
                <option class="user-item" value="active-users">{% trans 'Active Users' %}</option>
              </select>
              <a href="/{{ LANGUAGE_CODE }}{% url 'accounts:common_user_activity' %}?period=month&block=all-info"
                  class="waves-effect waves-light btn btn-primary white-text users-activity">
                  {% trans "Download activity" %}
              </a>
            </div>
         </div>
        </div>

        {% if action_form and actions_on_top and cl.show_admin_actions %}
        {% admin_actions %}
        {% endif %}
        {% if cl.date_hierarchy or cl.list_filter or cl.search_fields %}
        <div class="card filters-card">
            <div class="card-content">
                <span class="card-title">{% trans 'Filter' %}</span>
                {% block search %}{{ block.super }}{% endblock %}

                {% block filters %}
                  {{ block.super }}
                {% endblock %}

                {% block date_hierarchy %}{{ block.super }}{% endblock %}
                <div class="clearfix"></div>
            </div>
            <div class="card-action">&nbsp;</div>
        </div>
        {% endif %}
    </div>
    {% endif %}
</form>

{% if has_add_permission %}
{% url cl.opts|admin_urlname:'add' as add_url %}
<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves-effect waves-light red z-depth-2" href="{% add_preserved_filters add_url is_popup to_field %}">
        <i class="large material-icons">add</i>
    </a>
</div>
{% endif %}

<form id="changelist-search" action="?" method="get">
    <input type="hidden" id="searchbar_hidden"/>
    {% for pair in cl.params.items %}
    {% ifnotequal pair.0 'q' %}<input type="hidden" name="{{ pair.0 }}" value="{{ pair.1 }}"/>{% endifnotequal %}
    {% endfor %}
</form>
{% endblock %}

lifeline-backend-master/apps/accounts/templates/accounts/common_activity_report.html
{% load i18n %}
<html lang="en">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<head>
  <style>
    @font-face { font-family: Arial; src: url(fonts/Roboto-Regular.ttf);}
    @page {
        margin: 2cm;
        @frame footer_frame {
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 30pt;
        }
    }
    .underline {
        text-decoration: underline;
    }
    .content-header {
        margin-top: 40px;
        margin-bottom: 10px;
        font-weight: bold;
        font-size: 20px;
    }
    .concerns {
        margin-top: 30px;
    }
    .concerns-item {
        margin: 0;
    }
    .bold {
        font-weight:bold;
    }
    .footer {
       text-align: right;
       font-size: 12px;
       color: gray;
    }
    .type-title {
        font-size: 24px;
        color: blue;
    }
    body {
        font-size: 16px;
    }
  </style>
</head>
<body>
  <table>
     <tr>
        <th style="text-align:left"><img width="400" src="{{ logo }}" alt="logo"></th>
        <th style="text-align:right">
            <div  class="underline type-title">{{ type|upper }}</div>
            <span>{{ created }}</span>
        </th>
     </tr>
  </table>
  {% if all %}
    <h1 class="concerns">{% trans 'Report displays data for all time' %}</h1>
  {% else %}
    <h1 class="concerns">{% trans 'Report displays data' %} {% trans 'from' %} {{ prev }} {% trans 'to' %} {{ next }}</h1>
  {% endif %}


  {% if block == 'created' or block == 'all-info' %}
    <p class="underline concerns bold">{% trans 'Files were created' %}: {{ active_files.count }}</p>
    {% for file in active_files %}
      <div>{{ forloop.counter }}) {% trans 'Patient' %}: {{file.patient}} {% trans 'File' %}: {{ file }}, {% trans 'admission' %}: {{ file.created.date }}</div>
    {% endfor %}
  {% endif %}

  {% if block == 'archived' or block == 'all-info' %}
    <p class="underline concerns bold">{% trans 'Files were archived' %}: {{ archived_files.count }}</p>
    {% for file in archived_files %}
      <div>{{ forloop.counter }}) {% trans 'Patient' %}: {{file.patient}} {% trans 'File' %}: {{ file }}, {% trans 'released' %}: {{ file.closed_since }}</div>
    {% endfor %}
  {% endif %}

  {% if block == 'active-users' or block == 'all-info' %}
    <p class="underline concerns bold">{% trans 'Active users' %}: {{ users.count }}</p>
    {% for user in users %}
      <div>{{ forloop.counter }}) {{ user }}</div>
    {% endfor %}
  {% endif %}

  <div id="footer_content" class="footer">
    <br>
    {% trans 'Common Activity report, created by' %}: {{ user.username }} <pdf:pagenumber>/<pdf:pagecount>
  </div>
</body>
</html>

lifeline-backend-master/apps/accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}
Hello {{ user }},
You have already registered on {{ site_name }} or asked about access recovery for your account.
{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}s://{{ domain }}/auth/new-password?uid={{ uid }}&token={{ token }}
{% endblock %}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

lifeline-backend-master/apps/accounts/templates/accounts/user_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}

{% block extrahead %}
{{ block.super }}
<script src="{% static 'accounts/js/email-invitation.js' %}"></script>
<script src="{% static 'accounts/js/select-patient.js' %}"></script>
{% endblock %}

{% block object-tools-items %}
{% if perms.accounts.view_adminactivity and perms.accounts.view_activity %}
    <li class="collection-item upload-user">
        <p><strong>{% trans 'Select patient' %}</strong></p>
        <input type="text" class="patient-input" placeholder="{% trans 'Filter patients by name' %}">
        <select class="select-patient">
            <option class="user-item" value="">---------</option>
            {% for patient in patients %}
                <option class="user-item" value="{{ patient.pk }}">{{ patient.full_name }}</option>
            {% endfor %}
        </select>
        <p><strong>{% trans 'Select start date' %}</strong></p>
        <input class="vDateField start-activity" data-date-format="Y-m-d" data-form-control="date" size="10" type="text" placeholder="YYYY-MM-DD">
        <p><strong>{% trans 'Select end date' %}</strong></p>
        <input class="vDateField end-activity" data-date-format="Y-m-d" data-form-control="date" size="10" type="text" placeholder="YYYY-MM-DD">
        <form>
            <small class="error" style="display:none;">{% trans 'End date should be later than start date.' %}</small>
        </form>
        <div class="upload-button-block" style="padding-bottom: 55px; text-align: center">
            <p><strong>{% trans 'Download activity for selected user' %}</strong></p>
            <a href="/{{ LANGUAGE_CODE }}{% url 'accounts:user_activity' %}?user={{ original.pk }}"
                class="waves-effect waves-light btn btn-primary white-text user-activity">{% trans "Download activity" %}
            </a>
        </div>
    </li>
{% endif %}
<li class="collection-item">
    {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
    <a href="{% add_preserved_filters history_url %}" class="historylink"><i class="left material-icons">history</i> {% trans "History" %}</a>
</li>
<li class="collection-item" style="padding-bottom: 25px;padding-top: 25px; text-align: center">
    <p><strong>{% trans 'Send invitation email to' %} {{ adminform.form.instance.email }}</strong></p>
    <button class="waves-effect waves-light btn btn-primary white-text send-email"
            data-url="{% url 'accounts:rest_password_reset' %}"
            data-language="{{ LANGUAGE_CODE }}"
            data-email="{{ adminform.form.instance.email }}">{% trans "Send email" %}
    </button>
</li>

{% endblock %}